#!/usr/bin/env python3

# java -cp "$FUZZER/repo/daikon.jar" daikon.Daikon "$DAIKON_OUTPUT_PATH/decls.decls" --corpus "$TARGET/corpus12/$PROGRAM" --cmd "$OUT/$PROGRAM $ARGS" --invs "$DAIKON_OUTPUT_PATH/daikon.txt"

import sys
import os
import shlex

script_dir = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))

invscov_outpath = os.getenv("INVSCOV_OUTPUT_PATH")
if invscov_outpath is None:
    invscov_outpath = "invscov_output"
    print("WARN: INVSCOV_OUTPUT_PATH env not set, fallback to default 'invscov_output'")

daikon_path = os.path.join(script_dir, "..", "daikon.jar")
if os.getenv("DAIKON_PATH"):
    daikon_path = os.getenv("DAIKON_PATH")

if len(sys.argv) < 3:
    print("USAGE: learn-invariants CORPUS_DIR PROGRAM ARGS...")
    exit(1)

corpus = sys.argv[1]
command = " ".join(shlex.quote(x) for x in sys.argv[2:])

print('java -cp "' + daikon_path + '" daikon.Daikon "' + invscov_outpath + '/decls.decls" --corpus "' + corpus + '" --cmd ' + shlex.quote(command) + ' --invs "' + invscov_outpath + '/daikon.txt"\n')
os.system('time java -cp "' + daikon_path + '" daikon.Daikon "' + invscov_outpath + '/decls.decls" --corpus "' + corpus + '" --cmd ' + shlex.quote(command) + ' --invs "' + invscov_outpath + '/daikon.txt"')
